### PR TITLE
Fixes/Improvements made after testing with Ade's Windows machine.

### PR DESCRIPTION
**Pull request by TKMacmillan**
1) The React preset is added to get the es2015 preset working on Windows.  _The walking dead component is converted to es6 as an example._

2) In the console's output, 'found an error' is displayed in red text to make it easier to pinpoint Gulp transform errors.

3) When Gulp displays an error, Ade/other developers no longer need to restart Gulp. Changes to fix errors will be picked up automatically.

### CODE REVIEW

**Comment by PrimeLens** [comment]
add a comment to say what gulp-plumber does.  also revert away from ES6 notation for existing pages. create a new tv show/movie page and dedicate that to demonstrate that we can use ES6. thanks

**Comment by TKMacmillan** [comment]
This pull request has been updated.

**Comment by PrimeLens** [comment]
can you please remove all changes to 
parentsadvisory
rc.fireflyPageComponent
rc.dexterPageComponent
rc.homePageComponent
rc.thronesPageComponent

**Comment by PrimeLens** [comment]
whoops these are in the compiled files. can you give me a fresh set of compiled files. 
"gulp clean"  
"gulp build"

**Comment by TKMacmillan** [comment]
The files have been recompiled.

**Pull request merged**
